### ISSUE TITLE
generator raised StopIteration

### ISSUE THREAD

**Issue by Zahrun** [D-Brox/pysheng3#2]
I’m trying to get this working but I get this exception when I do Check:
```
[11:11:04] Checking book: "ID"
[11:11:04] Book ID: "ID"
[11:11:05] Info: attribution="Author"
[11:11:05] Info: title="Title"
[11:11:05] Info: total pages="pages"
[11:11:05] generator raised StopIteration
[11:11:05] Check book error
```
And the same when I do Execute:
```
[11:12:12] Page_start: 1, Page end: "pages"
[11:12:12] Book ID: "ID"
[11:12:14] Info: attribution="Author"
[11:12:14] Info: title="Title"
[11:12:14] Info: total pages=287
[11:12:14] job error: generator raised StopIteration
```
With the following errors:
```
Traceback (most recent call last):
  File "gui.py", line 140, in get_info
    raise StopIteration(info)
StopIteration: {'prefix': 'https://books.google.co.in/books?id=SOMEIDHERE&lpg=PP1', 'page_ids': ['PP1', 'PT5', 'PT7', 'PT8', 'PT9', 'PT10', 'PT11', 'PT12', 'PT13', 'PT14', 'PT15', 'PT16', 'PT17', 'PT18', 'PT19', 'PT20', 'PT21', 'PT22', 'PT23', 'PT24', 'PT25', 'PT26', 'PT27', 'PT28', 'PT29', 'PT30', 'PT31', 'PT32', 'PT33', 'PT34', 'PT35', 'PT36', 'PT37', 'PT38', 'PT39', 'PT40', 'PT41', 'PT42', 'PT43', 'PT44', 'PT45', 'PT46', 'PT47', 'PT48', 'PT49', 'PT50', 'PT51', 'PT52', 'PT53', 'PT54', 'PT55', 'PT56', 'PT57', 'PT58', 'PT59', 'PT60', 'PT61', 'PT62', 'PT63', 'PT64', 'PT65', 'PT66', 'PT67', 'PT68', 'PT69', 'PT70', 'PT71', 'PT72', 'PT73', 'PT74', 'PT75', 'PT76', 'PT77', 'PT78', 'PT79', 'PT80', 'PT81', 'PT82', 'PT83', 'PT84', 'PT85', 'PT86', 'PT87', 'PT88', 'PT89', 'PT90', 'PT91', 'PT92', 'PT93', 'PT94', 'PT95', 'PT96', 'PT97', 'PT98', 'PT99', 'PT100', 'PT101', 'PT102', 'PT103', 'PT104', 'PT105', 'PT106', 'PT107', 'PT108', 'PT109', 'PT110', 'PT111', 'PT112', 'PT113', 'PT114', 'PT115', 'PT116', 'PT117', 'PT118', 'PT119', 'PT120', 'PT121', 'PT122', 'PT123', 'PT124', 'PT125', 'PT126', 'PT127', 'PT128', 'PT129', 'PT130', 'PT131', 'PT132', 'PT133', 'PT134', 'PT135', 'PT136', 'PT137', 'PT138', 'PT139', 'PT140', 'PT141', 'PT142', 'PT143', 'PT144', 'PT145', 'PT146', 'PT147', 'PT148', 'PT149', 'PT150', 'PT151', 'PT152', 'PT153', 'PT154', 'PT155', 'PT156', 'PT157', 'PT158', 'PT159', 'PT160', 'PT161', 'PT162', 'PT163', 'PT164', 'PT165', 'PT166', 'PT167', 'PT168', 'PT169', 'PT170', 'PT171', 'PT172', 'PT174', 'PT177', 'PT178', 'PT180', 'PT181', 'PT182', 'PT186', 'PT190', 'PT191', 'PT193', 'PT194', 'PT195', 'PT197', 'PT198', 'PT199', 'PT201', 'PT202', 'PT203', 'PT204', 'PT205', 'PT206', 'PT207', 'PT208', 'PT209', 'PT210', 'PT212', 'PT213', 'PT214', 'PT216', 'PT219', 'PT220', 'PT221', 'PT222', 'PT223', 'PT224', 'PT226', 'PT227', 'PT228', 'PT229', 'PT230', 'PT231', 'PT232', 'PT233', 'PT235', 'PT236', 'PT238', 'PT239', 'PT240', 'PT242', 'PT243', 'PT244', 'PT245', 'PT246', 'PT248', 'PT249', 'PT252', 'PT254', 'PT255', 'PT256', 'PT257', 'PT258', 'PT259', 'PT260', 'PT261', 'PT262', 'PT263', 'PT264', 'PT265', 'PT266', 'PT267', 'PT269', 'PT270', 'PT271', 'PT273', 'PT274', 'PT275', 'PT276', 'PT277', 'PT279', 'PT281', 'PT282', 'PT283', 'PT284', 'PT285', 'PT286', 'PT287', 'PT289', 'PT290', 'PT293', 'PT294', 'PT295', 'PT296', 'PT297', 'PT298', 'PT300', 'PT302', 'PT303', 'PT304', 'PT305', 'PT306', 'PT307', 'PT310', 'PT326', 'PT327', 'PT328', 'PT329', 'PT330', 'PT331', 'PT332', 'PT333', 'PT334', 'PT335', 'PT336', 'PT337', 'PT338', 'PT339', 'PT340', 'PT341', 'PT342'], 'title': 'SOMETITLEHERE', 'attribution': 'SOMEAUTHORHERE', 'max_resolution': (1280, 1705)}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui.py", line 253, in check_book
    info = yield _from(get_info(widgets, cover_url, opener))
  File "yieldfrom.py", line 36, in _process
    nested_yielded = nested_gen.send(nested_tosend)
  File "yieldfrom.py", line 30, in _process
    yielded = gen.send(tosend)
RuntimeError: generator raised StopIteration
Traceback (most recent call last):
  File "gui.py", line 140, in get_info
    raise StopIteration(info)
StopIteration: {'prefix': 'https://books.google.co.in/books?id=SOMEIDHERE&lpg=PP1', 'page_ids': ['PP1', 'PT5', 'PT7', 'PT8', 'PT9', 'PT10', 'PT11', 'PT12', 'PT13', 'PT14', 'PT15', 'PT16', 'PT17', 'PT18', 'PT19', 'PT20', 'PT21', 'PT22', 'PT23', 'PT24', 'PT25', 'PT26', 'PT27', 'PT28', 'PT29', 'PT30', 'PT31', 'PT32', 'PT33', 'PT34', 'PT35', 'PT36', 'PT37', 'PT38', 'PT39', 'PT40', 'PT41', 'PT42', 'PT43', 'PT44', 'PT45', 'PT46', 'PT47', 'PT48', 'PT49', 'PT50', 'PT51', 'PT52', 'PT53', 'PT54', 'PT55', 'PT56', 'PT57', 'PT58', 'PT59', 'PT60', 'PT61', 'PT62', 'PT63', 'PT64', 'PT65', 'PT66', 'PT67', 'PT68', 'PT69', 'PT70', 'PT71', 'PT72', 'PT73', 'PT74', 'PT75', 'PT76', 'PT77', 'PT78', 'PT79', 'PT80', 'PT81', 'PT82', 'PT83', 'PT84', 'PT85', 'PT86', 'PT87', 'PT88', 'PT89', 'PT90', 'PT91', 'PT92', 'PT93', 'PT94', 'PT95', 'PT96', 'PT97', 'PT98', 'PT99', 'PT100', 'PT101', 'PT102', 'PT103', 'PT104', 'PT105', 'PT106', 'PT107', 'PT108', 'PT109', 'PT110', 'PT111', 'PT112', 'PT113', 'PT114', 'PT115', 'PT116', 'PT117', 'PT118', 'PT119', 'PT120', 'PT121', 'PT122', 'PT123', 'PT124', 'PT125', 'PT126', 'PT127', 'PT128', 'PT129', 'PT130', 'PT131', 'PT132', 'PT133', 'PT134', 'PT135', 'PT136', 'PT137', 'PT138', 'PT139', 'PT140', 'PT141', 'PT142', 'PT143', 'PT144', 'PT145', 'PT146', 'PT147', 'PT148', 'PT149', 'PT150', 'PT151', 'PT152', 'PT153', 'PT154', 'PT155', 'PT156', 'PT157', 'PT158', 'PT159', 'PT160', 'PT161', 'PT162', 'PT163', 'PT164', 'PT165', 'PT166', 'PT167', 'PT168', 'PT169', 'PT170', 'PT171', 'PT172', 'PT174', 'PT177', 'PT178', 'PT180', 'PT181', 'PT182', 'PT186', 'PT190', 'PT191', 'PT193', 'PT194', 'PT195', 'PT197', 'PT198', 'PT199', 'PT201', 'PT202', 'PT203', 'PT204', 'PT205', 'PT206', 'PT207', 'PT208', 'PT209', 'PT210', 'PT212', 'PT213', 'PT214', 'PT216', 'PT219', 'PT220', 'PT221', 'PT222', 'PT223', 'PT224', 'PT226', 'PT227', 'PT228', 'PT229', 'PT230', 'PT231', 'PT232', 'PT233', 'PT235', 'PT236', 'PT238', 'PT239', 'PT240', 'PT242', 'PT243', 'PT244', 'PT245', 'PT246', 'PT248', 'PT249', 'PT252', 'PT254', 'PT255', 'PT256', 'PT257', 'PT258', 'PT259', 'PT260', 'PT261', 'PT262', 'PT263', 'PT264', 'PT265', 'PT266', 'PT267', 'PT269', 'PT270', 'PT271', 'PT273', 'PT274', 'PT275', 'PT276', 'PT277', 'PT279', 'PT281', 'PT282', 'PT283', 'PT284', 'PT285', 'PT286', 'PT287', 'PT289', 'PT290', 'PT293', 'PT294', 'PT295', 'PT296', 'PT297', 'PT298', 'PT300', 'PT302', 'PT303', 'PT304', 'PT305', 'PT306', 'PT307', 'PT310', 'PT326', 'PT327', 'PT328', 'PT329', 'PT330', 'PT331', 'PT332', 'PT333', 'PT334', 'PT335', 'PT336', 'PT337', 'PT338', 'PT339', 'PT340', 'PT341', 'PT342'], 'title': 'SOMETITLEHERE', 'attribution': 'SOMEAUTHORHERE', 'max_resolution': (1280, 1705)}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui.py", line 253, in check_book
    info = yield _from(get_info(widgets, cover_url, opener))
  File "yieldfrom.py", line 36, in _process
    nested_yielded = nested_gen.send(nested_tosend)
  File "/yieldfrom.py", line 30, in _process
    yielded = gen.send(tosend)
RuntimeError: generator raised StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yieldfrom.py", line 42, in _process
    yielded2 = gen.throw(exc)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "asyncjobs.py", line 131, in _advance_task_cb
    self._advance_task_step(generator, method, result)
  File "asyncjobs.py", line 141, in _advance_task_step
    new_task = getattr(generator, method)(result)
RuntimeError: generator raised StopIteration
```
And then
```
Traceback (most recent call last):
  File "gui.py", line 140, in get_info
    raise StopIteration(info)
StopIteration: {'prefix': 'https://books.google.co.in/books?id=BOOKIDHERE&lpg=PP1', 'page_ids': ['PP1', 'PT5', 'PT7', 'PT8', 'PT9', 'PT10', 'PT11', 'PT12', 'PT13', 'PT14', 'PT15', 'PT16', 'PT17', 'PT18', 'PT19', 'PT20', 'PT21', 'PT22', 'PT23', 'PT24', 'PT25', 'PT26', 'PT27', 'PT28', 'PT29', 'PT30', 'PT31', 'PT32', 'PT33', 'PT34', 'PT35', 'PT36', 'PT37', 'PT38', 'PT39', 'PT40', 'PT41', 'PT42', 'PT43', 'PT44', 'PT45', 'PT46', 'PT47', 'PT48', 'PT49', 'PT50', 'PT51', 'PT52', 'PT53', 'PT54', 'PT55', 'PT56', 'PT57', 'PT58', 'PT59', 'PT60', 'PT61', 'PT62', 'PT63', 'PT64', 'PT65', 'PT66', 'PT67', 'PT68', 'PT69', 'PT70', 'PT71', 'PT72', 'PT73', 'PT74', 'PT75', 'PT76', 'PT77', 'PT78', 'PT79', 'PT80', 'PT81', 'PT82', 'PT83', 'PT84', 'PT85', 'PT86', 'PT87', 'PT88', 'PT89', 'PT90', 'PT91', 'PT92', 'PT93', 'PT94', 'PT95', 'PT96', 'PT97', 'PT98', 'PT99', 'PT100', 'PT101', 'PT102', 'PT103', 'PT104', 'PT105', 'PT106', 'PT107', 'PT108', 'PT109', 'PT110', 'PT111', 'PT112', 'PT113', 'PT114', 'PT115', 'PT116', 'PT117', 'PT118', 'PT119', 'PT120', 'PT121', 'PT122', 'PT123', 'PT124', 'PT125', 'PT126', 'PT127', 'PT128', 'PT129', 'PT130', 'PT131', 'PT132', 'PT133', 'PT134', 'PT135', 'PT136', 'PT137', 'PT138', 'PT139', 'PT140', 'PT141', 'PT142', 'PT143', 'PT144', 'PT145', 'PT146', 'PT147', 'PT148', 'PT149', 'PT150', 'PT151', 'PT152', 'PT153', 'PT154', 'PT155', 'PT156', 'PT157', 'PT158', 'PT159', 'PT160', 'PT161', 'PT162', 'PT163', 'PT164', 'PT165', 'PT166', 'PT167', 'PT168', 'PT169', 'PT170', 'PT171', 'PT172', 'PT174', 'PT177', 'PT178', 'PT180', 'PT181', 'PT182', 'PT186', 'PT190', 'PT191', 'PT193', 'PT194', 'PT195', 'PT197', 'PT198', 'PT199', 'PT201', 'PT202', 'PT203', 'PT204', 'PT205', 'PT206', 'PT207', 'PT208', 'PT209', 'PT210', 'PT212', 'PT213', 'PT214', 'PT216', 'PT219', 'PT220', 'PT221', 'PT222', 'PT223', 'PT224', 'PT226', 'PT227', 'PT228', 'PT229', 'PT230', 'PT231', 'PT232', 'PT233', 'PT235', 'PT236', 'PT238', 'PT239', 'PT240', 'PT242', 'PT243', 'PT244', 'PT245', 'PT246', 'PT248', 'PT249', 'PT252', 'PT254', 'PT255', 'PT256', 'PT257', 'PT258', 'PT259', 'PT260', 'PT261', 'PT262', 'PT263', 'PT264', 'PT265', 'PT266', 'PT267', 'PT269', 'PT270', 'PT271', 'PT273', 'PT274', 'PT275', 'PT276', 'PT277', 'PT279', 'PT281', 'PT282', 'PT283', 'PT284', 'PT285', 'PT286', 'PT287', 'PT289', 'PT290', 'PT293', 'PT294', 'PT295', 'PT296', 'PT297', 'PT298', 'PT300', 'PT302', 'PT303', 'PT304', 'PT305', 'PT306', 'PT307', 'PT310', 'PT326', 'PT327', 'PT328', 'PT329', 'PT330', 'PT331', 'PT332', 'PT333', 'PT334', 'PT335', 'PT336', 'PT337', 'PT338', 'PT339', 'PT340', 'PT341', 'PT342'], 'title': 'BOOKTITLEHERE', 'attribution': 'BOOKAUTHORHERE', 'max_resolution': (1280, 1705)}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui.py", line 164, in download_book
    info = yield _from(get_info(widgets, cover_url, opener))
  File "yieldfrom.py", line 36, in _process
    nested_yielded = nested_gen.send(nested_tosend)
  File "yieldfrom.py", line 30, in _process
    yielded = gen.send(tosend)
RuntimeError: generator raised StopIteration
Traceback (most recent call last):
  File "gui.py", line 140, in get_info
    raise StopIteration(info)
StopIteration: {'prefix': 'https://books.google.co.in/books?id=SOMEIDHERE&lpg=PP1', 'page_ids': ['PP1', 'PT5', 'PT7', 'PT8', 'PT9', 'PT10', 'PT11', 'PT12', 'PT13', 'PT14', 'PT15', 'PT16', 'PT17', 'PT18', 'PT19', 'PT20', 'PT21', 'PT22', 'PT23', 'PT24', 'PT25', 'PT26', 'PT27', 'PT28', 'PT29', 'PT30', 'PT31', 'PT32', 'PT33', 'PT34', 'PT35', 'PT36', 'PT37', 'PT38', 'PT39', 'PT40', 'PT41', 'PT42', 'PT43', 'PT44', 'PT45', 'PT46', 'PT47', 'PT48', 'PT49', 'PT50', 'PT51', 'PT52', 'PT53', 'PT54', 'PT55', 'PT56', 'PT57', 'PT58', 'PT59', 'PT60', 'PT61', 'PT62', 'PT63', 'PT64', 'PT65', 'PT66', 'PT67', 'PT68', 'PT69', 'PT70', 'PT71', 'PT72', 'PT73', 'PT74', 'PT75', 'PT76', 'PT77', 'PT78', 'PT79', 'PT80', 'PT81', 'PT82', 'PT83', 'PT84', 'PT85', 'PT86', 'PT87', 'PT88', 'PT89', 'PT90', 'PT91', 'PT92', 'PT93', 'PT94', 'PT95', 'PT96', 'PT97', 'PT98', 'PT99', 'PT100', 'PT101', 'PT102', 'PT103', 'PT104', 'PT105', 'PT106', 'PT107', 'PT108', 'PT109', 'PT110', 'PT111', 'PT112', 'PT113', 'PT114', 'PT115', 'PT116', 'PT117', 'PT118', 'PT119', 'PT120', 'PT121', 'PT122', 'PT123', 'PT124', 'PT125', 'PT126', 'PT127', 'PT128', 'PT129', 'PT130', 'PT131', 'PT132', 'PT133', 'PT134', 'PT135', 'PT136', 'PT137', 'PT138', 'PT139', 'PT140', 'PT141', 'PT142', 'PT143', 'PT144', 'PT145', 'PT146', 'PT147', 'PT148', 'PT149', 'PT150', 'PT151', 'PT152', 'PT153', 'PT154', 'PT155', 'PT156', 'PT157', 'PT158', 'PT159', 'PT160', 'PT161', 'PT162', 'PT163', 'PT164', 'PT165', 'PT166', 'PT167', 'PT168', 'PT169', 'PT170', 'PT171', 'PT172', 'PT174', 'PT177', 'PT178', 'PT180', 'PT181', 'PT182', 'PT186', 'PT190', 'PT191', 'PT193', 'PT194', 'PT195', 'PT197', 'PT198', 'PT199', 'PT201', 'PT202', 'PT203', 'PT204', 'PT205', 'PT206', 'PT207', 'PT208', 'PT209', 'PT210', 'PT212', 'PT213', 'PT214', 'PT216', 'PT219', 'PT220', 'PT221', 'PT222', 'PT223', 'PT224', 'PT226', 'PT227', 'PT228', 'PT229', 'PT230', 'PT231', 'PT232', 'PT233', 'PT235', 'PT236', 'PT238', 'PT239', 'PT240', 'PT242', 'PT243', 'PT244', 'PT245', 'PT246', 'PT248', 'PT249', 'PT252', 'PT254', 'PT255', 'PT256', 'PT257', 'PT258', 'PT259', 'PT260', 'PT261', 'PT262', 'PT263', 'PT264', 'PT265', 'PT266', 'PT267', 'PT269', 'PT270', 'PT271', 'PT273', 'PT274', 'PT275', 'PT276', 'PT277', 'PT279', 'PT281', 'PT282', 'PT283', 'PT284', 'PT285', 'PT286', 'PT287', 'PT289', 'PT290', 'PT293', 'PT294', 'PT295', 'PT296', 'PT297', 'PT298', 'PT300', 'PT302', 'PT303', 'PT304', 'PT305', 'PT306', 'PT307', 'PT310', 'PT326', 'PT327', 'PT328', 'PT329', 'PT330', 'PT331', 'PT332', 'PT333', 'PT334', 'PT335', 'PT336', 'PT337', 'PT338', 'PT339', 'PT340', 'PT341', 'PT342'], 'title': 'BOOKTITLEHERE', 'attribution': 'BOOKAUTHORHERE', 'max_resolution': (1280, 1705)}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui.py", line 164, in download_book
    info = yield _from(get_info(widgets, cover_url, opener))
  File "yieldfrom.py", line 36, in _process
    nested_yielded = nested_gen.send(nested_tosend)
  File "yieldfrom.py", line 30, in _process
    yielded = gen.send(tosend)
RuntimeError: generator raised StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yieldfrom.py", line 42, in _process
    yielded2 = gen.throw(exc)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "asyncjobs.py", line 131, in _advance_task_cb
    self._advance_task_step(generator, method, result)
  File "asyncjobs.py", line 141, in _advance_task_step
    new_task = getattr(generator, method)(result)
RuntimeError: generator raised StopIteration
```
Any idea?

**Comment by D-Brox** [comment]
Welp, I'd need to investigate.
I recently saw a video about this behavior change, btw, related to [this PEP](https://peps.python.org/pep-0479/).

**Comment by D-Brox** [comment]
Hopefully fixed with this https://github.com/D-Brox/pysheng3/blob/55a780d208585676af3b9a661804e3ef9039b1a0/pysheng/gui.py#L137
Not sure if it's working as indented tho

**Comment by CarGusMQ** [comment]
Hi,

I got the same problem for GUI, also when I try through command line I got this error:

Traceback (most recent call last):
  File "/home/ecosistemicas/.local/bin/pysheng", line 6, in <module>
    sys.exit(pysheng.main(sys.argv[1:]))
  File "/home/ecosistemicas/.local/lib/python3.10/site-packages/pysheng/download.py", line 171, in main
    for _, page, image_data in download_book(url, page_start, page_end):
  File "/home/ecosistemicas/.local/lib/python3.10/site-packages/pysheng/download.py", line 133, in download_book
    page_html = page_html.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 145: invalid continuation byte

Installation was done by conda Py3 enviroment.

**Comment by D-Brox** [comment]
@CarGusMQ The codec is probably ASCII instead of UTF-8 there. I've located the issue, but I still need to test the fix, can you provide me the url used?

**Comment by D-Brox** [comment]
@CarGusMQ Possibly fixed with 28e4709
