### ISSUE TITLE
system-wide installation fails

### ISSUE THREAD

**Issue by Zahrun** [D-Brox/pysheng3#3]
```
sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from pysheng import VERSION
  File "pysheng/__init__.py", line 1, in <module>
    from download import *
ModuleNotFoundError: No module named 'download'
```

**Comment by LinuxAndCoffee** [comment]
I am having the same issue, whether I use the install for local user or system-wide

**Comment by D-Brox** [comment]
Ye, I fixed this on the `master` branch a while back, but the default branch was configured to be `main`. I just noticed this today, and switched them
