### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by abeillino2go** [D-Brox/pysheng3#6]
On Debian sid the installation cancels
```console
sudo python3 setup.py install 
Traceback (most recent call last):
  File "/home/roland/temp/pysheng-master/setup.py", line 4, in <module>
    from pysheng import VERSION
  File "/home/roland/temp/pysheng-master/pysheng/__init__.py", line 1, in <module>
    from pysheng.download import *
  File "/home/roland/temp/pysheng-master/pysheng/download.py", line 27, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
```
Tried system-wide and user installation. Both failed. Used repo via git clone an your archive via zip file.

**Comment by D-Brox** [comment]
It's possibly an issue caused by debian now following [PEP668](https://peps.python.org/pep-0668/). Not sure how I can fix this, but I think using `pyproject.toml` instead of `setup.py` should do the trick.

For now, it's at least installable using a conda environment (that's how I was testing on my machine).

**Comment by abeillino2go** [comment]
Thanks. Tried it also on Archlinux:

```
sudo python3 setup.py install

/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
zip_safe flag not set; analyzing archive contents...
pysheng.__pycache__.gui.cpython-310: module references __file__
```

**Comment by D-Brox** [comment]
@abeillino2go Possibly fixed with 5e2d2d6
